### ISSUE TITLE
1.8 Crash from server side

### ISSUE THREAD

**Issue by Raumis** [TehNut/IronBackpacks#1]
Tested 1.8 version on client and everything seemed fine, loaded on server and crashed.

http://paste.debian.net/333199/

**Comment by TehNut** [comment]
Welp. I'm an idiot. Initialized a client only class on the server... Hehe...

Also, this fork was actually merged into the official repo and released on CurseForge. All future updates will go there as well. I don't have access to push builds to Curse, though, so I'll poke you with one here.

**Comment by TehNut** [comment]
[This](http://tehnut.info/share/IronBackpacks-1.8-1.0.4-CUSTOM.jar) should hold you over until the official version updates. That link will be removed in 30 days, so don't use it for anything permanent.

**Comment by Raumis** [comment]
Thanks :)
